### PR TITLE
Post on concurrency, synchrony and event source mapping.

### PR DESCRIPTION
**Pull request by ranvo**
Please let know what you guys think about it, or if there's any inaccuracy in it.

### CODE REVIEW

**Comment by ranvo** [comment]
Thanks for the review and changes. They better the post quite a bit! And I see that they are published as well. :)

**Comment by adnanrahic** [comment]
Yeah, the post is great! Keep them coming. We'd love to publish more. :smile:

**Comment by ranvo** [comment]
I would like to know more about Dashbird and it's features a little more
in-depth. I have talked with Annika about it too. Let me know, if we can
have a chat about it and come up with some ideas to market the product
better. :)

**Comment by adnanrahic** [comment]
Sure! We'll stay in touch.

**Pull request merged**
